### PR TITLE
Removed avplayerLayer & MoviePlayer from pod

### PR DESCRIPTION
**Pull request by rohshar6**
# Description

GIF:
ezgif com-gif-maker (1)

* Removed AVPlayerLayer & MoviePlayer From Pod.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] It requires unit tests.
- [ ] It doesn't require unit tests.

**Test Configuration**:
* iOS Simulator Version: iOS 15.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by urmit-chauhan — COMMENTED** [review]
should we remove VideoPlayer.swift?

**Comment by rohshar6** [comment]
> should we remove VideoPlayer.swift?

Already removed, @urmit-chauhan only AVPlayerLayer is left (this has AVPlayer and is present in the sample app).
Pod has only 3 files:
1. OSATVideoComposition
2. OSATAnnotation
3. OSATVideoCompositionError

**Comment by urmitchauhan** [comment]
> > should we remove VideoPlayer.swift?
> 
> Already removed, @urmit-chauhan only AVPlayerLayer is left (this has AVPlayer and is present in the sample app). Pod has only 3 files:
> 
> 1. OSATVideoComposition
> 2. OSATAnnotation
> 3. OSATVideoCompositionError

OK, then let's discuss and more simplify it further.
**APPROVED**

**Review by urmitchauhan — APPROVED** [review]

**Review by urmit-chauhan — APPROVED** [review]
> > should we remove VideoPlayer.swift?
> 
> Already removed, @urmit-chauhan only AVPlayerLayer is left (this has AVPlayer and is present in the sample app). Pod has only 3 files:
> 
> 1. OSATVideoComposition
> 2. OSATAnnotation
> 3. OSATVideoCompositionError

OK, then let's discuss and more simplify it further.
**APPROVED**

**Review by snbehar — APPROVED** [review]

**Review by snehilbehar — APPROVED** [review]

**Pull request merged**
