### PR TITLE
PR to add SwiftUI changes for OSAT view

### PR DESCRIPTION
**Pull request by rohshar6**

### CODE REVIEW

**Review by urmit-chauhan — COMMENTED** [review]
FrameWork side LGTM.
Can we remove outdated code that is no longer required?
There are 3–4 items lacking on the example app side. will speak over the call.

**Comment by rohshar6** [comment]
> FrameWork side LGTM. Can we remove outdated code that is no longer required? There are 3–4 items lacking on the example app side. will speak over the call.

Can this PR go in, we can do cleanup of sample app in other PR's.

**Comment by rohshar6** [comment]
This PR mainly handles OSAT pod parity to mac, UI level changes are not there and will require some effort

**Review by urmitchauhan — APPROVED** [review]
LGTM Framework Parity

**Review by urmit-chauhan — APPROVED** [review]
LGTM Framework Parity

**Review by HemDutt — APPROVED** [review]

**Pull request merged**
